import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
// import { Suspense } from "react";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${dmSans.className} antialiased`}>
            <div className="root-layout"><Providers>{children}</Providers></div>
            <Toaster richColors closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}

//java -Djava.library.path=/home/joanna-maj/Downloads/dynamodb_local/DynamoDBLocal_lib -jar /home/joanna-maj/Downloads/dynamodb_local/DynamoDBLocal.jar -sharedDb -dbPath /home/joanna-maj/Desktop/learning-management-app/

